# Generated by Django 2.2 on 2020-08-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Product Images'},
        ),
    ]
